### ISSUE TITLE
Signed Widevine Content Key requests

### ISSUE THREAD

**Issue by mbonig** [Axinom/drm-quick-start#1]
I need to make a Widevine Request to the Axinom key server to get a content key, are there any examples in your code to show putting together a signed request, with the sha1 and aes-cbc hashing and encryption specifically?

**Comment by sandersaares** [comment]
Hi!

Interactions with the Axinom Key Server are out of scope of this "DRM quick start" sample project. At the moment, we do not have any public samples for interacting with that particular service. However, there should be private documentation available to you via the Axinom DRM customer portal. Please open a private thread with your Axinom contact person for more info.

You can always drop a mail at info@axinom.com if you are not sure who to contact or are having trouble reaching the right person.
