### ISSUE TITLE
When trying to open up an Evaluation account i get the following error.

### ISSUE THREAD

**Issue by subhranshudas** [Axinom/drm-quick-start#14]
Referring the guide on - https://github.com/Axinom/drm-quick-start#sample-scenario-2-creating-your-own-license-tokens

I am facing the below issue. Tried multiple times!!! 
Any help is appreciated.

<img width="931" alt="screen shot 2018-03-19 at 11 28 26 am" src="https://user-images.githubusercontent.com/6158624/37608611-01f43a9c-2b69-11e8-9c1c-365868c4ba0a.png">

**Comment by jjauch** [comment]
This was fixed. Please try again.

**Comment by subhranshudas** [comment]
I get error while signing.
![screen shot 2018-03-20 at 8 03 44 am](https://user-images.githubusercontent.com/6158624/37656230-75320992-2c15-11e8-8642-e0e703d86c6d.png)

**Comment by jjauch** [comment]
Coincidentally, the Adobe e-sign service was down at the same time. Now it's up again. Should work now.

**Comment by subhranshudas** [comment]
I tried again, i was able to sign the Adobe sign in page, but saw a different format this time with prices and all. Not sure about whether i will be charged or not? Since this was an evaluation account i have signed up. Please let me know if its otherwise.
email provided-- subhranshu.das@globallogic.com

**Comment by jjauch** [comment]
Forgot to mention that this issue was solved already in March. For a short time the link was pointing to the wrong document (service agreement instead of the NDA).
Now everything works as expected.
