### ISSUE TITLE
Invalid DRM message. The value of the communication key ID property is invalid.

### ISSUE THREAD

**Issue by eva-bi** [Axinom/drm-quick-start#16]
My steps
- receiced "Service Fact Sheet" pdf
- created Secrets.json with my `communicationKeyId` & `communicationKey`
- created my own video as `Sample scenario 3`
- added this video into VideoDatabase.js
BUT when i play this video i got a error msg like below
http://prntscr.com/jwjb25
I really tried with other videos or other keyID

**Comment by Heronyme** [comment]
Hello!

Can you verify that the **Communication Key Id** in the Secrets.json file (which you copy-pasted from the Fact Sheet) has exactly the correct structure as shown in the Quick Start guide (same amount of characters and dashes, no extra spaces or punctuation):

```
{
    "communicationKeyId": "cffd95ba-aada-445b-b4ad-e8f322cf576a",
    "communicationKey": "092B1EFD61770602833E1621451A99092B1EFD61770602833E1621451A999999"
}
```

This error comes if the Communication Key ID value is not a GUID string.

**Comment by Heronyme** [comment]
It appears that the Fact Sheet you were provided contained an invalid Communication Key Id and all your steps were likely correct. A corrected Fact Sheet is being provided to you. Sorry about that!

Let us know if you encounter any other issues.

**Comment by eva-bi** [comment]
thanks  @Heronyme
i received the new communication keyid. My demo worked.
