### ISSUE TITLE
unable to play video.

### ISSUE THREAD

**Issue by ryankumar** [Axinom/drm-quick-start#17]
when i compiled programme, i got one url  "http://localhost:8120/" and copied and past it on browser,but it shows "Cannot GET /". can you help me in this.

**Comment by ryankumar** [comment]
when i did inspect on consol the following things are showing there.
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>


</body></html>

**Comment by Heronyme** [comment]
Hi. Was the server app started succesfully? I.e. when you did `node Server.js`, was the output:
```
No Secrets.json file found - only the built-in sample videos can be viewed.
Verifying integrity of video definition: Axinom demo video
The website is now available at http://localhost:8120
Press Control+C to shut down the application.
```

**Comment by ryankumar** [comment]
yes. server app started succesfully after node Server.js. and i got also 
No Secrets.json file found - only the built-in sample videos can be viewed.
Verifying integrity of video definition: Axinom demo video
The website is now available at http://localhost:8120
Press Control+C to shut down the application.

i copied the website and pasted on Firefox broser. but it's not working.

**Comment by Heronyme** [comment]
Are you using this on Linux? I just tried on Linux myself and got the same issue.  

It was resolved by renaming the "Index.html" (under /Website) to "index.html" with lower-case "i". 

Can you try this and see if it solves the issue for you too? Then we'll fix it.

**Comment by ryankumar** [comment]
yes. it is working now. thank you so much.

**Comment by ryankumar** [comment]
But i have one more doubt. Is that video encrypted previously or when we run that on browser at that time it is encrypted ??????

**Comment by Heronyme** [comment]
Yes that video is encrypted and the browser's content decryption module (CDM) decrypts it on-the-fly. 

See "Understanding sample scenario 1" and other sections for more info on what happens.

**Comment by ryankumar** [comment]
if it is encrypted then the content is secured or not

**Comment by Heronyme** [comment]
@ryankumar Closed this as the original issue is solved. Feel free to open a new one if you have more questions about the quick start guide.

Regarding previous question. It depends what you consider "secured content". The video you played was encrypted and can not be played without decrypting, so secure in that sense. Although as part of "Scenario #1" all the credentials used by the DRM workflow to get the correct decryption key for playback were hardcoded, so anyone can try things out, and so in that sense it's not secure. 

Please see the other scenarios and the "Moving onward to real-world usage" section to see how to secure your content in a production scenario.

**Comment by ryankumar** [comment]
@Heronyme  Thank you so much for your all answer.

**Comment by Heronyme** [comment]
@ryankumar And thank you for the issue report.
