### ISSUE TITLE
It doesn´t work on Firefox, IE or Edge

### ISSUE THREAD

**Issue by ThiagoMiranda** [Axinom/drm-quick-start#2]
Hi. 
Thanks for the great drm-quick-start project. It´s very simple to test and figure out how it works.
I´m evaluating some DRM solutions for my company but we need it to work in IE 11+, Edge and Firefox. Unfortunately your example ( I´m using it without any modifications ) doesn´t. Do you guys support these browsers?

Thanks!

**Comment by sandersaares** [comment]
The DRM quick start, without any modifications, should indeed work on all of those players. What exactly are the problems you are experiencing? Please provide exact steps to reproduce and any output from the browser console. A network trace (either from the browser's network tracing tool, if available, or [Fiddler]()http://www.telerik.com/fiddler) might also be helpful for diagnostics.

We have a deployment of this codebase up at https://drm-quick-start.azurewebsites.net/ - does the problem also reproduce with that deployment?

**Comment by ThiagoMiranda** [comment]
Thanks for the quick answer.
Actually my steps are very simple:
Just click on the "Axinom demo video" link and when the player starts it keeps loading like this:
![captura de tela 2016-09-15 as 14 32 36](https://cloud.githubusercontent.com/assets/141922/18560312/68f29e7e-7b51-11e6-95f3-24ebab12aea9.png)
This happens on the IE11+ too.

**Comment by sandersaares** [comment]
I see a red license request in that log but no details. Please provide a network capture of a failing playback at https://drm-quick-start.azurewebsites.net to allow me to inspect the traffic in detail. There should not be any failing requests in the log like that, so something abnormal is definitely happening.

The easiest way to get a network capture is using [FiddlerCap](http://www.telerik.com/fiddler/fiddlercap). Note that you need to have the "Decrypt HTTPS traffic" checkbox checked in order for the capture to work.

Firefox requires you to manually configure the FiddlerCap root certificate as trusted, so it will likely be easiest just to get the capture using IE or Edge.

**Comment by ThiagoMiranda** [comment]
Sorry but I´ve tried to make FiddlerCap work on my Mac but it didn´t work at all.
I´m not sure if it helps but this is the calls that are failing ( on the https://drm-quick-start.azurewebsites.net/ ):

![captura de tela 2016-09-16 as 16 14 20](https://cloud.githubusercontent.com/assets/141922/18598384/d51760bc-7c28-11e6-8de3-5fb4e2ac7b79.png)

![captura de tela 2016-09-16 as 16 13 47](https://cloud.githubusercontent.com/assets/141922/18598394/dd8d2704-7c28-11e6-84a8-d57841da57a2.png)

![captura de tela 2016-09-16 as 16 16 16](https://cloud.githubusercontent.com/assets/141922/18598400/e930e528-7c28-11e6-8620-b356d18cd807.png)

![captura de tela 2016-09-16 as 16 13 57](https://cloud.githubusercontent.com/assets/141922/18598407/f0e84da6-7c28-11e6-9fd7-ddd9db15e25f.png)

**Comment by sandersaares** [comment]
I confirm this is a defect in the license server - your browser is, for some reason, sending the name of the "Origin" header as lowercase ("origin"). This is unusual and not normal behavior that we have seen from browsers so far. However, it does conform to the HTTP specification, so it is essentially valid.

We will enhance the license server to also accept "origin" in the next release. I will discuss it with the DRM team and see if I can get you a timeline on the fix being deployed.

Meanwhile, I would like to improve our understanding of real-world usage conditions by learning more about your scenario. I would be interested to know if there is something special that might be causing the "origin" header to be lowercase - are you using any special browser extensions that might be intercepting and modifying requests? All the browsers we have encountered so far use "Origin", with the first letter in upper case.

**Comment by sandersaares** [comment]
The DRM team reports that deployment of the fix is expected this week.

**Comment by ThiagoMiranda** [comment]
@sandersaares I´ve tested and it happens both on my local browsers and in the browsers of the browserstack.com so I don´t think it´s a plugin related issue.
Thanks for the fix =)

**Comment by sandersaares** [comment]
The error should now be corrected. Please try again and report back if you still see failures!

**Comment by sandersaares** [comment]
The version with the fix is currently being deployed. You might already see it in action, depending on your geographic location. Will inform once fully deployed!

**Comment by sandersaares** [comment]
The new version is now running on all the instances in the testing environment. Please try it and report back if you still have problems in the listed browsers!

**Comment by ThiagoMiranda** [comment]
It´s working now ( tested on Firefox and IE11+ ).
Thanks =)

**Comment by sandersaares** [comment]
What operating system are you using for testing IE11? Windows 7 and Windows 8 will not work, although Windows 8.1 and Windows 10 should work.

**Comment by ThiagoMiranda** [comment]
@sandersaares I´m using Windows 8.1 and Windows 10 on browserstack.com

**Comment by sandersaares** [comment]
Our hypothesis here is that this is a shortcoming of browserstack.com - it could be that the platform of that service is not compatible with PlayReady DRM. Have you been able to play any other PlayReady DRM protected video in Internet Explorer on that platform?

If not, please try instead on a physical desktop PC with a fully updated version of Windows. If this works, I suggest you contact Browserstack support.
