### ISSUE TITLE
Add Shaka Player Example with Fairplay

### ISSUE THREAD

**Issue by EyMaddis** [Axinom/drm-quick-start#23]
ShakaPlayer 2.5 supports Apple Fairplay, but I am struggling to get it to work with Axinom.

It would help to also have a reference implementation for the shaka player.

**Comment by Heronyme** [comment]
Hello! We are in the progress of updating the quick start, which will include replacing the existing players with just Shaka Player.

In the mean time, I can provide you a temporary link to the updated player code that has everything needed for Axinom integration, but may require some changes to work with the current quickstart guide. The code and comments in the following page source should give an idea how to make it work.

http://vtb.axinom.com/tmp/drm-quick-start-shaka-prototype.html
