### ISSUE TITLE
Axinom DRM Fact Sheet

### ISSUE THREAD

**Issue by tuannn-viosoft** [Axinom/drm-quick-start#3]
i'm trying to follow your ReadMe doc,
what is Axinom DRM Fact Sheet?

thanks.

**Comment by jurgenj** [comment]
Dear Tuan,

I see you have also submitted a demo account request - that is exactly what you need to do - you will receive NDA for signature and then we create a demo account for you - part of it will be also a Fact Sheet giving you access to the demo environment.

**Comment by tuannn-viosoft** [comment]
Dear Jurgenj

thanks, i understood.
i close the issue.

i try to find license server solution as Axinom's. 
actually we want to build the sever by ourselves, but it's not easy task. 
in order to that, we need to do smt with Google (get certificate), is it correct?
