### ISSUE TITLE
Axinom Factsheet

### ISSUE THREAD

**Issue by mr-asleep** [Axinom/drm-quick-start#30]
I have created an account for a free trial. I am still awaiting the fact sheet to continue following the rest of the tutorial. Can you speed that up?

**Comment by Nimasha-axinom** [comment]
Hi,
You can send an email to [product support]( support@axinom.com) to raise a ticket regarding this. Also, you can raise your request via the Feedback section in [our portal](https://portal.axinom.com/drm).

**Comment by Heronyme** [comment]
Closing the issue due to inactivity.
