### ISSUE TITLE
Creating a custom DRM License Server

### ISSUE THREAD

**Issue by WINOFFRG** [Axinom/drm-quick-start#37]
Hi! I have a senario where I have been provided with a video which is DRM Protected. For the video I have access to its KEYID, KEY and LICENSE URL. Now, since the Original License Server is in Development Mode and unstable. I am searching of some way to create my own license server.

`My Theory`: Since I have access to decryption keys, I just need to parse the license payload recieved in each request. Accordingly then I can play with various parameters like device type and issue the license.

Is it practically possible to achieve the above thing?

**Comment by Heronyme** [comment]
Hello WINOFFRG

If I got your question right:

1. It is possible to create your own license service only if you apply for and get the relevant SDKs from the DRM technology providers.

2. If you just want to play some DRM protected media and already have access to the decryption keys, then you can just decrypt the media and play it like a normal video. DRM is about securing decryption keys and enforcing playback rules.

Best regards
Axinom support

**Comment by WINOFFRG** [comment]
So, there is no way out to create server on our own for free? What do you mean by SDK here? Is it something specifically acquired from Google for Widevine? Let's us Axinom here is the DRM Provider, So for someone to create service like Axinom do they have to purchase something or get license to anything that requires DRM Implementation on server?

What my point is that since I have the Encrypted Video and keys to decrypt it as well, Clear Key simply breaks the meaning of protection so I am searching of some way to implement my own DRM server for free which could just send the license data protecting my keys.

**Comment by Heronyme** [comment]
Hello from the future. This repo didn't get much attention for while. Since I believe this issue is stale by now, closing it. But to try to answer the question still, yes, unfortunately one can not simply implement a DRM service simply for free. Some form of licensing and fees are required depending on technology.
